language: php
php:
    - "5.5"
    - "5.4"
    - "5.3"
before_script:
    - pear config-set auto_discover 1
    - pear install pear.phing.info/phing
    - cp phing/build.properties.travis phing/build.propertie
script: phing test
