language: php
php:
    - "5.5"
    - "5.4"
    - "5.3"
before_script:
    - pear config-set auto_discover 1
    - pear install pear.phing.info/phing
    - phpenv rehash
    - composer install --dev
    - cp phing/build.properties.travis phing/build.properties
script: phing
