language: php
php:
    - "5.5"
    - "5.4"
    - "5.3"
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq php5-xdebug
    - echo -e "\nAuto-discover pear channels and upgrade ..."
    - pear config-set auto_discover 1
    - pear -qq channel-update pear.php.net
    - pear -qq upgrade
    - echo "... OK"
    - echo -e "\nInstalling/upgrading phing ..."
    - which phing >/dev/null && pear upgrade pear.phing.info/phing || pear install --alldeps pear.phing.info/phing
    - phpenv rehash
    - phing -v 2>&1 >/dev/null && echo "... OK" || echo "... FAILED"
    - echo -e "\nCopying build.properties ..."
    - cp phing/build.properties.travis phing/build.properties
    - echo "... OK"
script: phing
